### ISSUE TITLE
Needs more cats

### ISSUE THREAD

**Issue by Blackbaud-CalebCopper** [Blackbaud-JasonRikard/GitHub-Training#7]
Testing how submitting an issue would work. Who is assigns and completes?

**Comment by Blackbaud-JasonRikard** [comment]
Typically the primary project maintainer or the person responsible for maintaining the related subsection would assign this issue if it needs fixing.  Since I'm the only collaborator in this repository with admin rights, I'm the only option for the assignee.

**Comment by Blackbaud-CalebCopper** [comment]
Thanks, Jason! I'll close this issue now.
